# template_config.toml
[args]
# server model
num_users = 100      # int: number of users: K
all_clients = false   # bool: aggregation over all clients true or false
# server train
epochs = 10          # int: rounds of training
bs = 64             # int: test batch size
frac = 0.80           # float: the fraction of clients: C
gpu = true              # int: gpu device
verbose = true       # bool: verbose print
# client model
model = "lenet"        # str: model name mobilenet, resnet18, lenet
num_classes = 10     # int: number of classes
num_channels = 3     # int: number of channels of images
norm = "batch_norm"  # str: batch_norm, layer_norm, or None
num_filters = 32     # int: number of filters for conv nets
#client train
lr = 0.01            # float: learning rate
device = 'cuda:0'       # str: client device
local_ep = 1         # int: the number of local epochs: 2
local_bs = 64        # int: local batch size: 10
stopping_rounds = 20  # int: rounds of early stopping
momentum = 0.5       # float: SGD momentum (default: 0.5)
# data configuration
dataset = "mnist"    # str: name of dataset cifar10, cifar100 or mnist
split = "user"       # str: train-test split type, user or sample
iid = "True"           # bool: whether i.i.d or not
# other configuration
seed = 1             # int: random seed (default: 1)
# defense function
aggregate_function = "fed_avg" # str: name of defense function layer_defense or fed_avg
# attack configuration
malicious_user_rate = 0.50 # float: malicious user number
attack_method = "trigger"